app:
  myport: ${PORT:0}
spring:
  application:
    name: twowatch-monolito
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}