
###### cria sala
POST http://localhost:9942/tw-salas-chat/sala-chat/criar
Content-Type: application/json

{
  "nome": "sala httpss",
  "filme": {
    "id": 2
  },
  "usuarios": [
    {
      "id": 1
    }
  ]
}

###