### busca todos
GET http://localhost:9942/monolito/usuario


### adiciona
POST http://localhost:9942/monolito/usuario/criar
Content-Type: application/json

{
  "nome": "ana"
}

###

### atualiza um
PUT http://localhost:9942/monolito/usuario/atualizar
Content-Type: application/json

{
  "id": 2,
  "nome": "joaozin3"
}

###

### remove um
DELETE http://localhost:9942/monolito/usuario/deletar
Content-Type: application/json

{
  "id": 1
}

###### cria sala
POST http://localhost:9942/monolito/sala-chat/criar
Content-Type: application/json

{
  "nome": "sala httpss",
  "filme": {
    "id": 2
  },
  "usuarios": [
    {
      "id": 1
    }
  ]
}

###