spring:
  application:
    name: infnet.twowatchv3.gateway
  cloud:
    gateway:
      routes:
        - id: users-monolito
          uri: lb://twowatch-monolito
          filters:
            - StripPrefix=1
          predicates:
            - Path=/monolito/**
        - id: posts
          uri: lb://twPosts
          filters:
            - StripPrefix=1
          predicates:
            - Path=/tw-posts/**
        - id: filmes
          uri: lb://twFilmes
          filters:
            - StripPrefix=1
          predicates:
            - Path=/tw-filmes/**
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
server:
  port: 9942
