spring:
  application:
    name: estatisticasWorker
  jpa:
    defer-datasource-initialization: true
  data:
    mongodb:
      uri:mongodb://localhost:27017/chat-estatisticas-worker
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""

server:
  port: 2042
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}