### POST filmes
POST http://localhost:9942/tw-filmes/filme/criar
Content-Type: application/json

{
  "title": "duro de matar"
}


### GET filmes

GET http://localhost:9942/tw-filmes/filme/listar


###

### GET filmes

GET http://localhost:9942/tw-filmes/filme/listar-paginado?page=1?limit=3

###