version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salasdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - twowatch-networ
      -
eureka-server:
  image: gabj/infnet-eureka-server
  build:
    context: ../twowatch-serv-eureka/
    dockerfile: Dockerfile
  ports:
    - "8761:8761"
  networks:
    - twowatch-networ

  tw-salachat-service:
    image: gabj/tw-salachat
    build:
      context: ../twSalachat/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - twowatch-networ

networks:
  twowatch-networ:

volumes:
  mysql-data: