### POST request to example server
POST http://localhost:9942/posts/criar
Content-Type: application/json

{
  "texto": " amanha vo ver himym ",
  "usuarioId": 1
}


### GET request to example server
GET http://localhost:8042/comentarios/listar


###